name: JSON Edit


on:
  workflow_dispatch:
    inputs:
      fbUrl:
        description: 'Stream/Video URL (Example: "https://www.facebook.com/steigennytt/videos/593749372505938/")'
        required: true
        type: string
      text:
        description: 'true = URL is a live stream, false = URL is a video'
        required: true
        default: 'Nordfold'
        type: choice
        options:
        - 'Nordfold'
        - 'Nordfold - Reprise'
jobs:
  jsonedit:
    runs-on: ubuntu-latest
    name: json-to-file
    steps:
    - uses: devops-actions/json-to-file@v1.0.0
      with:
        # The json you want to store
        json: '{"streamurl": "${{ inputs.fbUrl }}", "tekst": "${{ inputs.text }}"}'
        # The filename you want to store the json in
        filename: './nordfoldtest.json'
    - uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: '$\{{ secrets.TOKEN }}'
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: 'https://github.com/LagardMedia/lagard.no.git'
        # Destination branch to push changes
        branch: 'main' # optional, default is master
        # Determines if force push is used
        force: true
        # Determines if --tags is used
        tags: false
        # Directory to change to before pushing.
        directory: '.'
