name: JSON Edit


on:
  workflow_dispatch:
    inputs:
      fbUrl:
        description: 'Stream/Video URL (Example: "https://www.facebook.com/steigennytt/videos/593749372505938/")'
        required: true
        type: string
      text:
        description: 'true = URL is a live stream, false = URL is a video'
        required: true
        default: 'Nordfold'
        type: choice
        options:
        - 'Nordfold'
        - 'Nordfold - Reprise'
jobs:
  jsonedit:
    runs-on: ubuntu-latest
    name: json-to-file
    steps:
    - uses: devops-actions/json-to-file@v1.0.0
      with:
        # The json you want to store
        json: '{"streamurl": "${{ inputs.fbUrl }}", "tekst": "${{ inputs.text }}"}'
        # The filename you want to store the json in
        filename: '.\nordfoldtest.json'
    - run: pwd
